<?php
/* custom routes generated by CRUD */


/*Route::group(array('prefix' => 'admin/', 'middleware' => 'admin','as'=>'admin.'), function () {

Route::get('vessels', ['as'=> 'vessels.index', 'uses' => 'VesselController@index']);
Route::post('vessels', ['as'=> 'vessels.store', 'uses' => 'VesselController@store']);
Route::get('vessels/create', ['as'=> 'vessels.create', 'uses' => 'VesselController@create']);
Route::put('vessels/{vessels}', ['as'=> 'vessels.update', 'uses' => 'VesselController@update']);
Route::patch('vessels/{vessels}', ['as'=> 'vessels.update', 'uses' => 'VesselController@update']);
Route::get('vessels/{id}/delete', array('as' => 'vessels.delete', 'uses' => 'VesselController@getDelete'));
Route::get('vessels/{id}/confirm-delete', array('as' => 'vessels.confirm-delete', 'uses' => 'VesselController@getModalDelete'));
Route::get('vessels/{vessels}', ['as'=> 'vessels.show', 'uses' => 'VesselController@show']);
Route::get('vessels/{vessels}/edit', ['as'=> 'vessels.edit', 'uses' => 'VesselController@edit']);

});*/
