{{--custom menu items generated by CRUD--}}

{{--<li class="{{ Request::is('admin/vesselManufacturers*') ? 'active' : '' }}">
    <a href="{!! route('admin.vesselManufacturers.index') !!}">
    <i class="livicon" data-c="#6CC66C" data-hc="#6CC66C" data-name="home" data-size="18"
               data-loop="true"></i>
               VesselManufacturers
    </a>
</li>--}}

