<?php

namespace App\Http\Controllers;

use Braintree_ClientToken;

/**
 * Class BraintreeController
 * @package App\Http\Controllers
 */
class BraintreeController extends Controller
{
    /**
     * We will use ajax to set the generated token as the CLIENT-TOKEN-FROM-SERVER value.
     * Note: that braintree.js needs a client token generated by the Braintree server SDK for the payment form to be loaded
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function token()
    {
        return response()->json([
            'data' => [
                'token' => Braintree_ClientToken::generate(),
            ]
        ]);
    }
}
